export const initialState = {
    productList :[],  
    isLoader: false,
    isRegFormOpen: false,
    isLoginFormOpen: false,
    user: null,
    closeModal:false,
    globalError:'',
    categories:[],
    countries:[],
    notFound:false,
    notFoundCategory:false,
    isGuestPopUp:false,
    favoriteList:[],
    cartArray:[],
    isNotificationPopUp:false,
    notificationBoldMessage:'',
    notificationMessage:'',
    cartBubble:0,
    orderList:[],
    completedOrderArray:[],
    offset:0,
    orderHistory:[],
}